Repository jenkinsci/matrix-project-plugin, pull requests merged in 2020-06, with the labels that each got.

#62 Updated parent, deps, BOM
  pom.xml
  src/test/java/hudson/matrix/MatrixProjectTest.java
Labels: dependencies

#64 Terminology update
  README.md
  src/main/resources/hudson/matrix/LabelAxis/help-labels_nl.html
  src/main/resources/hudson/matrix/LabelAxis/help.html
  src/main/resources/hudson/matrix/LabelAxis/help_zh_TW.html
  src/main/resources/hudson/matrix/LabelExpAxis/help-labelExpr.html
  src/main/resources/hudson/matrix/LabelExpAxis/help-labelExpr_zh_TW.html
  src/main/resources/hudson/matrix/LabelExpAxis/help.html
  src/main/resources/hudson/matrix/LabelExpAxis/help_zh_TW.html
  src/main/resources/hudson/matrix/Messages.properties
  src/main/resources/hudson/matrix/Messages_pt.properties
  src/main/resources/hudson/matrix/Messages_pt_BR.properties
  src/main/resources/hudson/matrix/Messages_zh_CN.properties
  src/main/resources/hudson/matrix/Messages_zh_TW.properties
  src/main/webapp/help/matrix/combinationfilter_de.html
  src/main/webapp/help/matrix/combinationfilter_zh_TW.html
  src/test/java/hudson/matrix/AxisTest.java
Labels: documentation

#65 Fixing ClassCastException found by PCT
  src/main/java/hudson/tasks/test/MatrixTestResult.java
Labels: bug

#66 Fix build on Java11 because of PowerMock
  src/test/java/hudson/matrix/CombinationFilterUsingBuildParamsTest.java
Labels: tests
