Repository jenkinsci/matrix-project-plugin, pull requests merged in 2021-06, with the labels that each got.

#72 [JENKINS-65398] Terminology update
  README.md
  src/main/java/hudson/matrix/FilterScript.java
  src/main/java/hudson/matrix/MatrixConfiguration.java
  src/main/resources/hudson/matrix/MatrixProject/help-slaveAffinity.html
  src/main/resources/hudson/matrix/Messages_da.properties
  src/main/webapp/help/matrix/combinationfilter.html
  src/test/java/hudson/matrix/MatrixProjectTest.java
Labels: documentation

#74 Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`
  src/test/java/hudson/matrix/RestartingRestoreTest.java
Labels: tests

#73 Stop using deprecated `Util#join`
  src/main/java/hudson/matrix/Axis.java
  src/main/java/hudson/matrix/LabelAxis.java
  src/main/java/hudson/matrix/MatrixProject.java
Labels: chore

#70 [JENKINS-64107] Convert SSHD module to a plugin
  pom.xml
Labels: dependencies
