Repository jenkinsci/matrix-project-plugin, pull requests merged in 2022-03, with the labels that each got.

#75 EOL JSR 305
  src/main/java/hudson/matrix/AxisList.java
  src/main/java/hudson/matrix/DefaultMatrixExecutionStrategyImpl.java
  src/main/java/hudson/matrix/MatrixBuild.java
  src/main/java/hudson/matrix/MatrixChildParametersAction.java
  src/main/java/hudson/matrix/MatrixConfiguration.java
  src/main/java/hudson/matrix/MatrixConfigurationSorterDescriptor.java
  src/main/java/hudson/matrix/MatrixProject.java
  src/main/java/hudson/matrix/listeners/MatrixBuildListener.java
Labels: dependencies

#77 Integrate security fix from 1.20
  pom.xml
  src/main/java/hudson/matrix/LabelAxis.java
  src/main/resources/hudson/matrix/LabelAxis/config.jelly
Labels: bug

#78 [JENKINS-66450] Utilize new build status
  src/main/resources/hudson/matrix/MatrixBuild/ajaxMatrix.jelly
  src/main/resources/hudson/matrix/MatrixProject/ajaxMatrix.jelly
Labels: enhancement

#80 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore

#85 Dependency updates
  pom.xml
  src/test/java/hudson/matrix/AxisTest.java
  src/test/java/hudson/matrix/CombinationFilterUsingBuildParamsTest.java
Labels: dependencies
