Repository jenkinsci/matrix-project-plugin, pull requests merged in 2023-08, with the labels that each got.

#168 Remove usages of Prototype
  src/main/resources/hudson/matrix/LabelAxis/config.jelly
Labels: developer

#169 Modernize to Jenkins 2.375.4
  pom.xml
Labels: dependencies

#157 [JENKINS-71272] ensure proper confirmDelete jelly is used
  src/main/resources/hudson/matrix/MatrixBuild/confirmDelete.jelly
  src/main/resources/hudson/matrix/MatrixRun/confirmDelete.jelly
Labels: enhancement

#170 Test on Java 21
  Jenkinsfile
Labels: chore
