Repository jenkinsci/matrix-project-plugin, pull requests merged in 2023-10, with the labels that each got.

#179 Forward compatibility with core version 2.422+
  src/test/java/hudson/matrix/AxisTest.java
Labels: tests

#173 Add Plugin Development Team to CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#174 Fix link text in README.md
  README.md
Labels: documentation

#178 style(MatrixTestResult): Increase column width for duration
  src/main/resources/hudson/tasks/test/MatrixTestResult/index.jelly
Labels: ui
