Repository jenkinsci/matrix-project-plugin, pull requests merged in 2024-05, with the labels that each got.

#194 Reduce `javax.servlet.ServletException` footprint
  src/main/java/hudson/matrix/MatrixConfiguration.java
Labels: developer

#183 Adapt to new build symbols (requires 2.434)
  pom.xml
  src/main/resources/hudson/matrix/MatrixBuild/ajaxMatrix.jelly
  src/main/resources/hudson/matrix/MatrixProject/ajaxMatrix.jelly
Labels: enhancement

#199 [JENKINS-73225] - Restore linking when multiple axes
  src/main/resources/hudson/matrix/MatrixBuild/ajaxMatrix.jelly
  src/main/resources/hudson/matrix/MatrixProject/ajaxMatrix.jelly
  src/main/resources/lib/hudson/matrix-project/matrix.jelly
Labels: bug
