Repository jenkinsci/matrix-project-plugin, pull requests merged in 2024-10, with the labels that each got.

#130 [JENKINS-69659] Un-inline multiple occurrences of JavaScript in Jelly templates
  src/main/java/hudson/matrix/LabelAxis.java
  src/main/java/hudson/matrix/MatrixProject.java
  src/main/resources/hudson/matrix/LabelAxis/config.jelly
  src/main/resources/hudson/matrix/LabelAxis/label-axis-resources.js
  src/main/resources/hudson/matrix/MatrixProject/configure-entries.jelly
  src/main/resources/lib/hudson/matrix-project/matrix-resources.js
  src/main/resources/lib/hudson/matrix-project/matrix.jelly
Labels: enhancement

#213 Reimplement the UI for `LabelAxis`
  pom.xml
  src/main/java/hudson/matrix/LabelAxis.java
  src/main/resources/hudson/matrix/LabelAxis/config.jelly
  src/main/resources/hudson/matrix/LabelAxis/label-axis.css
  src/main/resources/hudson/matrix/LabelAxis/label-axis.js
  src/main/resources/hudson/matrix/MatrixProject/configure-entries.jelly
Labels: enhancement

#231 Require Java 17 or newer; migrate to EE 9
  pom.xml
  src/main/java/hudson/matrix/Axis.java
  src/main/java/hudson/matrix/MatrixBuild.java
  src/main/java/hudson/matrix/MatrixConfiguration.java
  src/main/java/hudson/matrix/MatrixProject.java
  src/main/java/hudson/matrix/MatrixRun.java
Labels: internal

#236 Require 2.479.1 LTS or newer
  pom.xml
Labels: skip-changelog
